version: '3'
services:
  # app-container:
  #   container_name: app-container
  #   build:
  #     context: . 
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - .env
  #   networks:
  #     - app-name-network
  mysql:
    container_name: app-mysql
    image: mysql:5.7
    restart: always
    command: [--max-allowed-packet=67108864, --lower_case_table_names=1, --default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports: 
      - '3306:3306'
    # volumes:
    #   - db_data:/var/lib/mysql
    networks: 
      - app-name-network

networks:
  app-name-network:

volumes:
  db_data: