openapi: 3.0.3
info:
  title: Project API
  description: APIs for Project
  version: 1.0.0
  termsOfService: http://example.com/terms
  contact:
    name: API Support
    url: http://example.com/support
    email: support@api.com
  license:
    name: "MIT"
    url: https://opensource.org/licenses/MIT
servers:
- url: http://127.0.0.1:8080/api/v1
  description: Development server
- url: https://staging.project-server.com/v1
  description: Staging server
- url: https://api.project-server.com/v1
  description: Production server
tags:
- name: Post
  description: Post management endpoints
- name: Cash Advance Application
  description: Cash advance application management endpoints
paths:
  $ref: ./docs/api/paths/index.yaml
components:
  $ref: ./docs/api/components/index.yaml