openapi: 3.0.1
info:
  title: Project API
  description: APIs for Project
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Post
  description: Post management endpoints
paths:
  $ref: ./docs/api/paths/index.yaml
components:
  $ref: ./docs/api/components/index.yaml